---
- name: Install docker
  gather_facts: No
  hosts: vm

  tasks:
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

    - name: Install yum utils
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - epel-release
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - python-pip

    - name: Add Docker GPG key.
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      yum:
        name: docker-ce
        state: present
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      become: yes

    - name: Install Docker-py
      pip:
        name: docker-py

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes

    - name: data container
      docker_container:
        name: web
        image: nginx
        state: started
        ports:
          - "80:80"
...